<h2><?php echo $this->titulo; ?></h2>

<div class="box">
	<a href="<?php echo BASE_URL.'menus/cadastrar'; ?>" class="botao fr">Cadastrar</a>
</div>

<form method="post">
	<div class="box">
		<h2>Buscar menus:</h2>
		<p class="fl input margin5">
			<label>Nome:</label>
			<input type="text" name="buscar_nom"/>
		</p>
		<p class="fl input margin5">
			<label>Nome item:</label>
			<input type="text" name="buscar_item"/>
		</p>
		<p class="fl input margin5">
			<label>Url item:</label>
			<input type="text" name="buscar_url"/>
		</p>
		<p class="fl input margin5">
			<label>Status:</label>
			<select name="buscar_status">
				<option value="">Todos</option>
			<?php foreach($this->todosStatus as $status) { ?> 
				<option value="<?php echo $status['cod_status']; ?>"><?php echo $status['nom_status']; ?></option>
			<?php } ?>
			</select>
		</p>
		<input class="botao fr" name="buscar" type="submit" value="Buscar"/>
	</div>
</form>

<?php if(count($this->res) != 0) { ?>
<form method="post" action="<?php echo BASE_URL.'menus/excluir'; ?>">
	<div class="box">
		<table>
			<thead>
				<tr>
					<th class="tal"></th>
					<th class="tal">Código</th>
					<th class="tal">Nome</th>
					<th class="tal">Status</th>
					<th class="tac">Visualizar</th>
					<th class="tac">Alterar</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->res as $ln) { ?>
				<tr>
					<td class="tal width5"><input value="<?php echo $ln['cod_menu']; ?>" name="check[]" type="checkbox"/></td>
					<td class="tal"><?php echo '#'.$ln['cod_menu']?></td>
					<td class="tal"><?php echo $ln['nom_menu']?></td>
					<td class="tal"><?php echo $ln['nom_status']?></td>
					<td class="tac width5">
						<a href="<?php echo BASE_URL.'menus/visualizar/'.$ln['cod_menu']; ?>" class="botao fl">Visualizar</a>
					</td>
					<td class="tac width5">
						<a href="<?php echo BASE_URL.'menus/alterar/'.$ln['cod_menu']; ?>" class="botao fl amarelo">Alterar</a>
					</td>
				</tr>			
			<?php } ?>
			</tbody>
		</table>
		
		<table>
			<tbody>
				<!-- check.js esta em webroot/js -->
				<td class="tal"><input onclick="check();" type="checkbox"/>Selecionar todos</td>
				
				<td class="tac">
					<button class="botao_pg">Anterior</button>					
			
					<button class="botao_pg">1</button>			
				
					<button class="botao_pg select_pg">2</button>
				
					<button class="botao_pg">3</button>
									
					<button class="botao_pg">Próximo</button>
				</td>
				<td class="tar"><input class="botao fr vermelho" type="submit" name="excluir" value="Excluir selecionados"/></td>
			</tbody>
		</table>
	</div>
</form>
<?php } ?>
<?php 
	//destroi sessão de mensagens para quando refresh não continuar exibindo mensagens
	unset($_SESSION['_msg']);
?>