<h2><?php echo $this->titulo; ?></h2>

<div class="box">
	<a href="<?php echo BASE_URL.'menus'; ?>" class="botao fl">Voltar</a>
</div>

<div class="box">
	<p class="input">
		<label>Nome:</label>
		<input type="text" disabled="disabled" class="input_min width500" value="<?php echo isset($this->menus->nom_menu) ? $this->menus->nom_menu : null ?>"/>
	</p>
	<p class="input">
		<label>Status:</label>
		<input type="text" disabled="disabled" class="input_min width500" value="<?php echo isset($this->status->nom_status) ? $this->status->nom_status : null ?>"/>
	</p>
</div>

<?php if (count($this->menuItens) != 0 ) { ?>
	<div class="box">
		<h1>Este menu contém <?php echo count($this->menuItens ); ?> itens:</h1>
	</div>
	
	<?php foreach($this->menuItens as $ln) { ?>
	<div class="box">
		<p class="input">
			<label>Código do item:</label>
			<input type="text" disabled="disabled" class="input_min width500" value="<?php echo isset($ln['cod_menu_item']) ? $ln['cod_menu_item'] : null ?>"/>
		</p>
		<p class="input">
			<label>Nome do item:</label>
			<input type="text" disabled="disabled" class="input_min width500" value="<?php echo isset($ln['nom_item']) ? $ln['nom_item'] : null ?>"/>
		</p>
		<p class="input">
			<label>Url do item:</label>
			<input type="text" disabled="disabled" class="input_min width500" value="<?php echo isset($ln['url_item']) ? $ln['url_item'] : null ?>"/>
		</p>
	</div>
	<?php } ?>
<?php } ?>