<h2><?php echo $this->titulo; ?></h2>
<script>
	 $('.ckeditor').ckeditor();
</script>
<div class="box">
	<a href="<?php echo BASE_URL.'produtos'; ?>" class="botao fl">Voltar</a>
</div>
<form method="post">
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1">Produtos</a></li>
			<li><a href="#tabs-2">Imagens</a></li>
			<li><a href="#tabs-3">Configurações</a></li>
			<li><a href="#tabs-4">Dimensões</a></li>
		</ul>
		
		<div id="tabs-1">
			<p class="input required">
				<label>Nome:</label>
				<input type="text" name="nom_produto" maxlength="255" class="input_min" onkeyup="geraSlug(this.value)" value="<?php echo isset($this->produtos->nom_produto) ? $this->produtos->nom_produto : null ?>"/>
			</p>
			<p class="input">
				<label>Número:</label>
				<input type="text" name="num_produto" maxlength="150" class="input_min" value="<?php echo isset($this->produtos->num_produto) ? $this->produtos->num_produto : null ?>"/>
			</p>
			<p class="input">
				<label>Alerta do Estoque:</label>
				<input type="text" name="num_alerta" maxlength="11" class="input_min" value="<?php echo isset($this->produtos->num_estoque_alerta) ? $this->produtos->num_estoque_alerta : null ?>"/>
			</p>
			<p class="input required">
				<label>Valor (R$):</label>
				<input type="text" name="num_valor" maxlength="11" class="input_min" value="<?php echo isset($this->produtos->vlr_preco) ? $this->produtos->vlr_preco : null ?>"/>
			</p>
			<p class="input">
				<label>Descrição:</label>
				<textarea class="ckeditor" name="editor1"></textarea>
			</p>
			<p class="input">
				<label>Informação:</label>
				<textarea name="des_info"><?php echo isset($this->produtos->des_informacao) ? $this->produtos->des_informacao : null ?></textarea>
			</p>
			<p class="input">
				<label>Status:</label>
				<select name="ind_status">
				<?php foreach($this->todosStatus as $status) { ?> 
					<option value="<?php echo $status['cod_status']; ?>" <?php echo isset($this->produtos->cod_status) ? $status['cod_status'] == $this->produtos->cod_status ? 'selected="selected"' : '' : null ?>><?php echo $status['nom_status']; ?></option>
				<?php } ?>
				</select>
			</p>
		</div>
		
		<div id="tabs-2">
			<p class="input required">
				<label>Imagens:</label>
				<input type="file" name="imagem"/>
			</p>
		</div>
		
		<div id="tabs-3">
			<p class="input required">
				<label>Categorias:</label>
				<?php foreach($this->todasCategorias as $categorias) { ?> 
					<div class="checkbox">
						<input type="checkbox" name="categorias[]" <?php echo isset($this->categorias->cod_categoria) ? $categorias['cod_categoria'] == $this->categorias->cod_categoria ? 'checked="checked"' : '' : null ?>/><?php echo $categorias['nom_categoria']; ?></br>
					</div>
				<?php } ?>		
			</p></br>	
			<p class="input required">
				<label>Slug:
					<?php $mensagemSlug = "<strong>Slug</strong></br>Defina palavras chave para este produto. Elas ajudarão os buscadores, como o Google por exemplo, a encontrar seus produtos.</br>Palavras relacionadas ao produto. Sem acentos, números, caractéres especiais, e espaços devem ser substituidos por sinal negativo (-)."; ?>
					<a onmouseover="Tip('<?php echo $mensagemSlug; ?>')" onmouseout="UnTip()">(o que é?)</a>
				</label>
				<input type="text" name="url_slug" maxlength="255" class="input_min campoSlug" onkeyup="geraSlug(this.value)" value="<?php echo isset($this->categorias->url_slug) ? $this->categorias->url_slug : null ?>"/>
			</p>
			<p class="input">
				<label>Produtos Relacionados:</label>
				<select name="prod_relacionados">
					<option value="<?php echo $status['cod_status']; ?>" <?php echo isset($this->produtos->cod_status) ? $status['cod_status'] == $this->produtos->cod_status ? 'selected="selected"' : '' : null ?>><?php echo $status['nom_status']; ?></option>
				</select>
			</p>
		</div>
		
		<div id="tabs-4">
			<p class="input required">
				<label>Largura x Altura x Circunferência: 
					<?php $mensagemSlug = 'Defina as dimensões usando metros, centimetros.'; ?>
					<a onmouseover="Tip('<?php echo $mensagemSlug; ?>')" onmouseout="UnTip()">(o que é?)</a>
				</label>
				<input type="text" name="num_largura" maxlength="7" class="input_min width60 dimensoes" value="<?php echo isset($this->produtos->num_estoque_alerta) ? $this->produtos->num_estoque_alerta : null ?>"/>
				<input type="text" name="num_altura" maxlength="7" class="input_min width60 dimensoes" value="<?php echo isset($this->produtos->num_estoque_alerta) ? $this->produtos->num_estoque_alerta : null ?>"/>
				<input type="text" name="num_circunferência" maxlength="7" class="input_min width60 dimensoes" value="<?php echo isset($this->produtos->num_estoque_alerta) ? $this->produtos->num_estoque_alerta : null ?>"/>
			</p>  			<p class="input required">
				<label>Peso:
					<?php $mensagemSlug = 'Defina o peso do pacote completo usando kilo, gramas.'; ?>
					<a onmouseover="Tip('<?php echo $mensagemSlug; ?>')" onmouseout="UnTip()">(o que é?)</a>
				</label>
				<input type="text" name="num_peso" maxlength="8" class="input_min peso" value="<?php echo isset($this->produtos->num_estoque_alerta) ? $this->produtos->num_estoque_alerta : null ?>"/>
			</p>
		</div>
	</div>	
	
	<div class="box">
		<input class="botao fr" name="cadastrar" type="submit" value="Cadastrar"/>
	</div>
</form>