<h2><?php echo $this->titulo; ?></h2>

<div class="box">
	<a href="<?php echo BASE_URL.'clientes'; ?>" class="botao fl">Voltar</a>
</div>

<form method="post">
	<div class="box">
		<p class="error">Você irá excluir os seguintes clientes:</br></br>
			#01 - Marcos Souza</br>
			#02 - Juliano Silva</br>
			#05 - Rafaela Luisa</br>
			#09 - Marcos Paulo
			</br></br>Esta exclusão não podera ser desfeita!
		</p>
	</div>
	<div class="box">
		<input class="botao fr vermelho" name="confirma_excluir" type="submit" value="Excluir"/>
	</div>
</form>
