<h2><?php echo $this->titulo; ?></h2>

<div class="box">
	<a href="<?php echo BASE_URL.'clientes'; ?>" class="botao fl">Voltar</a>
</div>

<form method="post">
	<div class="box">
		<p class="error">
			Você irá excluir o(s) seguintes cliente(s):</br>
			<?php 
				foreach($this->selecionado as $ln) {
					echo '#'.$ln['cod_cliente'].' - '.$ln['nom_cliente'].'<br/>';
				}
			?>
			Esta exclusão não poderá ser desfeita.
		</p>
	</div>
	<div class="box">
		<input type="hidden" name="check" value="<?php echo $this->check; ?>"/>
		<input class="botao fr vermelho" name="confirma" type="submit" value="Excluir"/>
		<a href="<?php echo BASE_URL.'clientes'; ?>" class="botao fl amarelo">Cancelar</a>
	</div>
</form>
