<h2><?php echo $this->titulo; ?></h2>

<div class="box">
	<a href="<?php echo BASE_URL.'clientes/cadastrar'; ?>" class="botao fr">Cadastrar</a>
</div>

<form method="post">
	<div class="box">
		<h2>Buscar clientes:</h2>
		<p class="fl input margin5">
			<label>Nome:</label>
			<input type="text" name="buscar_nome"/>
		</p>
		<p class="fl input margin5">
			<label>E-mail:</label>
			<input type="text" name="buscar_email"/>
		</p>
		<p class="fl input margin5">
			<label>Nº RG:</label>
			<input type="text" class="rg" name="buscar_rg"/>
		</p>
		<p class="fl input margin5">
			<label>Nº CPF:</label>
			<input type="text" class="cpf" name="buscar_cpf"/>
		</p>
		<p class="fl input margin5">
			<label>Nº CNPJ:</label>
			<input type="text" class="cnpj" name="buscar_cnpj"/>
		</p>
		<input class="botao fl" name="buscar" type="submit" value="Buscar"/>
	</div>
</form>

<?php if(count($this->res) != 0) { ?>
<form method="post" action="<?php echo BASE_URL.'clientes/excluir'; ?>">
	<div class="box">
		<table>
			<thead>
				<tr>
					<th class="tal"></th>
					<th class="tal">Código</th>
					<th class="tal">Nome</th>
					<th class="tal">E-mail</th>
					<th class="tac">Telefones</th>
					<th class="tal">Tipo</th>
					<th class="tal">Visualizar</th>
					<th class="tal">Alterar</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->res as $ln) { ?>
				<tr>
					<td class="tal width5"><input value="<?php echo $ln['cod_cliente']; ?>" name="check[]" type="checkbox"/></td>
					<td class="tal"><?php echo '#'.$ln['cod_cliente']?></td>
					<td class="tal"><?php echo $ln['nom_cliente']?></td>
					<td class="tal"><?php echo $ln['des_email']?></td>
					<td class="tac"><?php echo $ln['num_telefone_fixo'].'<br/>'.$ln['num_telefone_celular']; ?></td>
					<td class="tal"><?php echo $ln['des_cliente_tipo']; ?></td>
					<td class="tal width5">
						<a href="<?php echo BASE_URL.'clientes/visualizar/'.$ln['cod_cliente']; ?>" class="botao fl">Visualizar</a>
					</td>
					<td class="tal width5">
						<a href="<?php echo BASE_URL.'clientes/alterar/'.$ln['cod_cliente']; ?>" class="botao fl amarelo">Alterar</a>
					</td>
				</tr>			
			<?php } ?>
			</tbody>
		</table>
		
		<table>
			<tbody>
				<!-- função check esta em js/check.js -->
				<td class="tal"><input onclick="check();" type="checkbox"/>Selecionar todos</td>
				
				<td class="tac">
					<button class="botao_pg">Anterior</button>					
			
					<button class="botao_pg">1</button>			
				
					<button class="botao_pg select_pg">2</button>
				
					<button class="botao_pg">3</button>
									
					<button class="botao_pg">Próximo</button>
				</td>
				<td class="tar"><input class="botao fr vermelho" type="submit" name="excluir" value="Excluir selecionados"/></td>
			</tbody>
		</table>
	</div>
</form>
<?php } ?>
<?php 
	//destroi sessão de mensagens para quando refresh não continuar exibindo mensagens
	unset($_SESSION['_msg']);
?>