<div class="box">
	<table>
		<thead>
			<tr>
				<th>#</th>
				<th>Nome</th>
				<th>Telefone</th>
				<th>Mensagem</th>
				<th>Status</th>
			</tr>
		</thead>	
		
		<tbody>
			<tr>
				<td>1</td>
				<td><a>Geremias</a></td>
				<td>47 3333-3333</td>
				<td>Teste de tabela</td>
				<td>Ativo</td>
			</tr>
			
			<tr>
				<td>1</td>
				<td>Geremias</td>
				<td>47 3333-3333</td>
				<td>Teste de tabela</td>
				<td>Ativo</td>
			</tr>
			
			<tr>
				<td>1</td>
				<td>Geremias</td>
				<td>47 3333-3333</td>
				<td>Teste de tabela</td>
				<td>Ativo</td>
			</tr>
			
			<tr>
				<td>1</td>
				<td>Geremias</td>
				<td>47 3333-3333</td>
				<td>Teste de tabela</td>
				<td>Ativo</td>
			</tr>
		</tbody>
	</table>
</div>